### ISSUE TITLE
Port forwarding for a specific iface

### ISSUE THREAD

**Issue by igoropaniuk** [saschpe/libvirt-hook-qemu#16]
Hi everyone,

Is it possible to setup port forwarding just for a specific network interface?
My case: I have two NICs: eth0, eth1. I want to have port forwarding just for incoming connections to eth0, but refuse all connection attempts to the same tcp port on eth1.
I've tried to play wth "public_ip" param, but unfortunately I didn't get it work, seems that I'm doint something wrong.

Thanks!

**Comment by igoropaniuk** [comment]
Seems that I've made a mistake somewhere, just rewrote json config once more, public_ip started working :)

**Comment by saschpe** [comment]
Issue can be closed?
