### ISSUE TITLE
Can't reach services from other host.

### ISSUE THREAD

**Issue by ricariel** [saschpe/libvirt-hook-qemu#19]
Hi
I'm using this hook to make for example https available to the world. When an other guest want to reach the webserver this timed out. What am i doing wrong or where can i fix this.

Thanks!

**Comment by kleest** [comment]
I've had a similar problem. My setup exemplified:  
Multiple VMs connected to one bridged interface in subnet 192.168.122.0/24.  
  
Host redirects traffic on public port to VM-1, let's say public port 80 and private port 8080. Public access works flawlessly but when I try to access the host's public address + public port from within VM-2 it fails. However, internal traffic using the private IP + private port works.  
  
I fixed this by doing the following changes:
```diff
diff --git a/hooks b/hooks
index 820cde0..22585ac 100755
--- a/hooks
+++ b/hooks
@@ -142,7 +142,7 @@ def populate_chains(dnat_chain, snat_chain, fwd_chain, public_ip, private_ip, do
                              "-d", public_ip, "--dport", str(public_port), "-j", "DNAT", "--to", dest] +
                             (["-s", source_ip] if source_ip else []))
             subprocess.call([IPTABLES_BINARY, "-t", "nat", "-A", snat_chain, "-p", protocol,
-                             "-s", private_ip, "-d", private_ip, "--dport", str(public_port), "-j", "MASQUERADE"])
+                             "-s", private_ip, "-d", private_ip, "--dport", str(private_port), "-j", "MASQUERADE"])
             interface = ["-o", domain["interface"]
                          ] if "interface" in domain else []
             subprocess.call([IPTABLES_BINARY, "-t", "filter", "-A", fwd_chain, "-p", protocol,
```
  
Note: The problem does not appear when using the same port number for both the public and private port.
